version: '3.8'

services:
  # Development Database
  postgres-dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=salesaide_dev
      - POSTGRES_USER=salesaide
      - POSTGRES_PASSWORD=salesaide_dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U salesaide -d salesaide_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
